import { NextRequest, NextResponse } from "next/server";
import type { ScoreResponse } from "@/lib/types";
interface ChatMessage { role: "user" | "assistant"; content: string; }
async function fetchMireyeField(lat: number, lng: number, fieldName: string): Promise<{ value: unknown; error?: string }> {
  const token = process.env.MIREYE_API_TOKEN ?? process.env.MIREYE_BEARER_TOKEN ?? process.env.MIREYE_API_KEY;
  if (!token) return { value: null, error: "Mireye not configured" };
  try { const res = await fetch("https://api.mireye.com/v1/fetch", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ lat, lng, fields: [fieldName] }), signal: AbortSignal.timeout(8000) }); if (!res.ok) return { value: null, error: `Mireye ${res.status}` }; const data = await res.json(); const fieldData = data?.fields?.[fieldName] ?? data?.[fieldName]; return { value: fieldData?.value ?? fieldData ?? null }; } catch (e) { return { value: null, error: String(e) }; }
}
function buildSystemContext(v: ScoreResponse, freshField?: { fieldName: string; value: unknown }): string {
  const freshSection = freshField ? `\nFRESH DATA FETCHED FOR THIS CONVERSATION:\n- ${freshField.fieldName}: ${String(freshField.value)} (fetched live from Mireye for this question — use this value in your answer)\n` : "";
  return `Address: ${v.displayAddress}; site type: ${v.score.siteType}; Site Score (displayed in UI): ${v.score.baseline.toFixed(1)}/100; Composite (unclamped, baseline × multiplier): ${v.score.composite.toFixed(1)}; Final (composite clamped to 100, for display only): ${v.score.final.toFixed(1)}/100; NOTE: When users ask "what is my score" they mean ${v.score.baseline.toFixed(1)} — the baseline displayed prominently in the UI. Do not refer to their score as ${v.score.final.toFixed(1)} unless specifically asked about the clamped final. multiplier: ${v.score.multiplier}; dimensions: ${JSON.stringify(v.score.dimensions)}; permitting flags: ${JSON.stringify(v.score.permittingFriction.flags)}; benchmark range: ${JSON.stringify(v.benchmark.monthlyRange)}; leverage summary: ${JSON.stringify(v.leverageSummary)}; data gaps: ${JSON.stringify(v.dataGaps)}; OpenCellID: ${JSON.stringify(v.intelligence?.opencellid ? { cells: v.intelligence.opencellid.cells.length, carriers: v.intelligence.opencellid.carriersPresent } : undefined)}${freshSection}\nINSTRUCTIONS: Write plain prose only: no markdown headers, bullets, or bold. Maximum 4 sentences for simple questions and 6–8 for complex questions. Never use the word "dimension"; say "component" or name it. When referencing the site score, say "${v.score.baseline.toFixed(0)}/100". If fresh data appears above, say "I just looked that up" and use it. If Mireye genuinely returns null, say so clearly and suggest contacting the carrier or commissioning a site survey.`;
}
export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null) as { messages?: ChatMessage[]; valuation?: ScoreResponse } | null;
  if (!body || !Array.isArray(body.messages) || !body.messages.length || body.messages.some((m) => !m || (m.role !== "user" && m.role !== "assistant") || typeof m.content !== "string") || body.messages.at(-1)?.role !== "user" || !body.valuation) return NextResponse.json({ ok: false, error: "messages and valuation are required" }, { status: 400 });
  const valuation = body.valuation; const lastUserMsg = body.messages[body.messages.length - 1].content;
  const hints: Array<{ pattern: RegExp; field: string }> = [{ pattern: /nearest antenna|closest antenna|antenna distance|how far.*antenna|antenna.*how far/i, field: "nearest_antenna_structure_distance_m" }, { pattern: /antenna type|tower type|structure type|what kind.*tower/i, field: "nearest_antenna_structure_type" }, { pattern: /drainage|soil drain/i, field: "soil_drainage_class" }, { pattern: /flood(plain)?/i, field: "within_floodplain_polygon" }, { pattern: /fiber|broadband/i, field: "fiber_broadband_available" }, { pattern: /slope|grade|incline/i, field: "slope_degrees" }, { pattern: /5g coverage/i, field: "mobile_5g_coverage_class" }];
  let freshFieldData: { fieldName: string; value: unknown } | undefined;
  for (const hint of hints) if (hint.pattern.test(lastUserMsg)) { const result = await fetchMireyeField(valuation.lat, valuation.lng, hint.field); if (result.value !== null && result.value !== undefined) freshFieldData = { fieldName: hint.field, value: result.value }; break; }
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return NextResponse.json({ ok: false, error: "Assistant unavailable" }, { status: 503 });
  const contents = [{ role: "user", parts: [{ text: `Use this valuation context as authoritative context:\n${buildSystemContext(valuation, freshFieldData)}` }] }, { role: "model", parts: [{ text: "Understood. I will answer using the provided valuation context." }] }, ...body.messages.map((m) => ({ role: m.role === "assistant" ? "model" : "user", parts: [{ text: m.content }] }))];
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents, generationConfig: { temperature: 0.4, maxOutputTokens: 800 } }) });
  if (!response.ok) return NextResponse.json({ ok: false, error: "Assistant unavailable" }, { status: 502 });
  const data = await response.json(); return NextResponse.json({ ok: true, answer: data.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text ?? "").join("") ?? "Unable to answer." });
}
