import { NextRequest, NextResponse } from "next/server";
import type { ScoreResponse } from "@/lib/types";
interface ChatMessage { role: "user" | "assistant"; content: string; }
function buildSystemContext(v: ScoreResponse) { return `Address: ${v.displayAddress}; site type: ${v.score.siteType}; Site Score (displayed in UI): ${v.score.baseline.toFixed(1)}/100; Composite (unclamped, baseline × multiplier): ${v.score.composite.toFixed(1)}; Final (composite clamped to 100, for display only): ${v.score.final.toFixed(1)}/100; NOTE: When users ask "what is my score" they mean ${v.score.baseline.toFixed(1)} — the baseline displayed prominently in the UI. The composite of ${v.score.composite.toFixed(1)} is shown separately as context. Do not refer to their score as ${v.score.final.toFixed(1)} unless specifically asked about the clamped final. multiplier: ${v.score.multiplier}; dimensions: ${JSON.stringify(v.score.dimensions)}; permitting flags: ${JSON.stringify(v.score.permittingFriction.flags)}; benchmark range: ${JSON.stringify(v.benchmark.monthlyRange)}; leverage summary: ${JSON.stringify(v.leverageSummary)}; data gaps: ${JSON.stringify(v.dataGaps)}; OpenCellID: ${JSON.stringify(v.intelligence?.opencellid ? { cells: v.intelligence.opencellid.cells.length, carriers: v.intelligence.opencellid.carriersPresent } : undefined)}; INSTRUCTIONS: Write in plain prose — no markdown headers (###), no bullet points, no bold (**text**). Use plain sentences and paragraph breaks only. Maximum 4 sentences for simple questions. For complex questions like "should I sell?", 6–8 sentences max. Never use the word "dimension" — say "component" or just name it (Coverage Necessity, Subscriber Value, Construction Cost). When referencing the site score, say "${v.score.baseline.toFixed(0)}/100" — not the composite or final values.`; }
export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null) as { messages?: ChatMessage[]; valuation?: ScoreResponse } | null;
  if (!body || !Array.isArray(body.messages) || !body.messages.length || body.messages.some((m) => !m || (m.role !== "user" && m.role !== "assistant") || typeof m.content !== "string") || body.messages.at(-1)?.role !== "user" || !body.valuation) return NextResponse.json({ ok: false, error: "messages and valuation are required" }, { status: 400 });
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return NextResponse.json({ ok: false, error: "Assistant unavailable" }, { status: 503 });
  const contents = [{ role: "user", parts: [{ text: `Use this valuation context as authoritative context:\n${buildSystemContext(body.valuation)}` }] }, { role: "model", parts: [{ text: "Understood. I will answer using the provided valuation context." }] }, ...body.messages.map((m) => ({ role: m.role === "assistant" ? "model" : "user", parts: [{ text: m.content }] }))];
  const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${apiKey}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ contents, generationConfig: { temperature: 0.4, maxOutputTokens: 800 } }) });
  if (!response.ok) return NextResponse.json({ ok: false, error: "Assistant unavailable" }, { status: 502 });
  const data = await response.json();
  return NextResponse.json({ ok: true, answer: data.candidates?.[0]?.content?.parts?.map((p: { text?: string }) => p.text ?? "").join("") ?? "Unable to answer." });
}
