import { Annotation, StateGraph } from "@langchain/langgraph";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { mcpTool } from "./mcp";
import { EvidenceRegistry, discover, type EvidenceCategory, type EvidenceRequest, type Location } from "./evidence";
import { mireyeProvider, openCellIdProvider } from "./providers";
import type { ScoreResponse, IntelligenceLayers } from "@/lib/types";

export const SignalRentState = Annotation.Root({
  address: Annotation<string>(), lat: Annotation<number | undefined>(), lng: Annotation<number | undefined>(), carrier: Annotation<string | undefined>(), offeredRate: Annotation<number | undefined>(), buyoutAmount: Annotation<number | undefined>(),
  resolvedLat: Annotation<number>(), resolvedLng: Annotation<number>(), displayAddress: Annotation<string>(), evidence: Annotation<any[]>({ reducer: (a, b) => [...(a ?? []), ...(b ?? [])], default: () => [] }), capabilities: Annotation<any[]>(), plannerOutput: Annotation<EvidenceRequest[]>(), executorOutput: Annotation<string[]>(), evidenceQuality: Annotation<{ enough: boolean; confidence: number; missing: string[] } | null>(), result: Annotation<ScoreResponse | null>(), error: Annotation<string | null>(),
});
type State = typeof SignalRentState.State;
const registry = new EvidenceRegistry(); registry.addProvider(mireyeProvider); registry.addProvider(openCellIdProvider);
const unwrap = (v: any) => v?.structuredContent ?? v?.data ?? v?.content ?? v;

async function resolveNode(state: State) { const response = unwrap(await mcpTool("mireye_lookup", { input: state.lat !== undefined && state.lng !== undefined ? `${state.lat},${state.lng}` : state.address })); if (response?.disposition === "clarify") return { error: `Address is ambiguous: ${(response.candidates ?? []).map((c: any) => c.label).join(" or ")}` }; if (response?.disposition === "no_match") return { error: "Address not found." }; const location = response.location ?? response; return { resolvedLat: Number(location.lat), resolvedLng: Number(location.lng), displayAddress: location.displayAddress ?? location.label ?? state.address }; }
async function discoverNode() { const capabilities = await discover(registry); console.info("[reasoning] discovery", { capabilityCount: capabilities.length }); return { capabilities }; }
async function plannerNode() { const plannerOutput: EvidenceRequest[] = [{ concept: "population and demand", category: "population", importance: "high", reason: "estimate subscriber value" }, { concept: "terrain, hazards, utilities and access", category: "hazard", importance: "high", reason: "estimate construction and permitting friction" }, { concept: "nearby towers, carriers and coverage", category: "coverage", importance: "high", reason: "estimate coverage necessity and competition" }]; console.info("[reasoning] planner output", plannerOutput); return { plannerOutput }; }
async function collectNode(state: State) { const location: Location = { lat: state.resolvedLat, lng: state.resolvedLng, displayAddress: state.displayAddress }; const batches = await Promise.all(registry.providerList().map((p) => p.collectEvidence(location, state.plannerOutput).catch((error) => [{ id: `${p.metadata().id}:error`, provider: p.metadata().id, category: ["unknown"] as EvidenceCategory[], summary: `Provider unavailable: ${String(error)}`, confidence: 0, importance: "high" as const, provenance: { source: p.metadata().name, retrievedAt: new Date().toISOString() }, timestamp: new Date().toISOString() }]))); const evidence = batches.flat(); registry.addEvidence(...evidence); const executorOutput = registry.providerList().map((p) => p.metadata().id); return { evidence, executorOutput }; }
async function assessEvidenceNode() { const evidence = registry.all(); const confidence = evidence.length ? evidence.reduce((sum, item) => sum + item.confidence, 0) / evidence.length : 0; const missing = ["population", "coverage", "hazard"].filter((category) => !evidence.some((item) => Array.isArray(item.category) && item.category.includes(category as any))); const quality = { enough: evidence.length > 0 && confidence >= .5 && missing.length < 3, confidence, missing }; console.info("[reasoning] evidence quality", { evidenceCount: evidence.length, confidence, missing, enough: quality.enough }); return { evidenceQuality: quality }; }
function parseModelResponse(content: unknown) { const text = Array.isArray(content) ? content.map((part: any) => typeof part === "string" ? part : part?.text ?? "").join("\n") : String(content ?? ""); const tagged = text.match(/<output>\s*([\s\S]*?)\s*<\/output>/i)?.[1]; const fenced = text.match(/```(?:json)?\s*([\s\S]*?)\s*```/i)?.[1]; const candidate = tagged ?? fenced ?? text.trim(); console.info("[reasoning] model response", { textLength: text.length, hasTaggedOutput: Boolean(tagged), hasFencedJson: Boolean(fenced) }); if (!candidate) throw new Error("Reasoner returned empty text"); try { const raw = JSON.parse(candidate); const parsed = raw?.score ? raw : raw?.result?.score ? raw.result : raw?.output?.score ? raw.output : raw; const leverage = parsed.leverageSummary ?? parsed.negotiationLeverage ?? parsed.negotiation_leverage ?? parsed.leverage ?? parsed.keyRisks ?? parsed.risks ?? parsed.strengths; if (!parsed.leverageSummary) parsed.leverageSummary = leverage ? (Array.isArray(leverage) ? leverage : [String(leverage)]) : []; console.info("[reasoning] parser result", { structuredJson: true, rawKeys: Object.keys(raw ?? {}), normalizedKeys: Object.keys(parsed ?? {}), unwrapped: parsed !== raw, leverageNormalized: Boolean(leverage && parsed?.leverageSummary) }); return { parsed, reasoning: text.match(/<reasoning>([\s\S]*?)<\/reasoning>/i)?.[1]?.trim() ?? "" }; } catch (error) { console.error("[reasoning] parser result", { structuredJson: false, error: String(error), candidateLength: candidate.length }); throw new Error(`Reasoner returned invalid JSON: ${String(error)}`); } }
async function reasonNode(state: State) { const model = new ChatGoogleGenerativeAI({ model: "gemini-3.1-flash-lite", temperature: 0, apiKey: process.env.GEMINI_API_KEY }); const prompt = `Location: ${state.displayAddress} (${state.resolvedLat}, ${state.resolvedLng})\nCarrier: ${state.carrier ?? "unknown"}\nOffered rate: ${state.offeredRate ?? "not provided"}\nBuyout: ${state.buyoutAmount ?? "not provided"}\nPlanner tasks: ${JSON.stringify(state.plannerOutput)}\nExecutor providers: ${JSON.stringify(state.executorOutput)}\nEvidence registry: ${JSON.stringify(state.evidence, null, 2)}`; const contract = "You are SignalRent's evidence-based valuation reasoner. Reason only from the evidence registry. Do not invent values, fields, providers, weights, scores, thresholds, or missing facts. Return one top-level JSON object with these exact UI contract keys: ok (true), address, displayAddress, lat, lng, score, benchmark, leverageSummary, dataGaps, reasoning. The score object must contain baseline, composite, multiplier, final, dimensions, permittingFriction, siteType, and dataGaps. The benchmark object must contain monthlyRange, annualRange, siteType, scoreBand, calibrationNote, baseValue, and priceBreakdown. Include explicit uncertainty in dataGaps and leverageSummary when evidence is missing. Never wrap the object under result, output, valuation, or any other key. You may optionally wrap JSON in <output> tags and reasoning text in <reasoning> tags."; console.info("[reasoning] final prompt", { promptLength: prompt.length, evidenceCount: state.evidence.length }); const message = await model.invoke([new SystemMessage(contract), new HumanMessage(prompt)]); let { parsed, reasoning } = parseModelResponse(message.content); if (!parsed.leverageSummary) { const repair = await model.invoke([new SystemMessage(`${contract} The prior object was missing leverageSummary. Return the complete same object, adding leverageSummary as an array of negotiation insights supported only by the supplied evidence.`), new HumanMessage(JSON.stringify({ valuation: parsed, evidence: state.evidence }))]); ({ parsed, reasoning } = parseModelResponse(repair.content)); console.info("[reasoning] schema repair", { attempted: true, hasLeverageSummary: Boolean(parsed.leverageSummary) }); } return { result: { ...parsed, reasoning, intelligence: {} as IntelligenceLayers } as ScoreResponse }; }
async function validateNode(state: State) { const missing = [!state.result?.score && "score", !state.result?.benchmark && "benchmark", !Array.isArray(state.result?.leverageSummary) && "leverageSummary"].filter(Boolean); const valid = missing.length === 0; console.info("[reasoning] validation", { valid, resultPresent: Boolean(state.result), resultKeys: state.result ? Object.keys(state.result) : [], missing }); if (!valid) return { error: `Reasoner returned an incomplete valuation result (missing: ${missing.join(", ")})` }; return { result: state.result }; }

export const graph = new StateGraph(SignalRentState).addNode("resolveLocation", resolveNode).addNode("discoverCapabilities", discoverNode).addNode("planEvidence", plannerNode).addNode("collectEvidence", collectNode).addNode("assessEvidence", assessEvidenceNode).addNode("reason", reasonNode).addNode("validate", validateNode).addEdge("__start__", "resolveLocation").addConditionalEdges("resolveLocation", (s) => s.error ? "__end__" : "discoverCapabilities").addEdge("discoverCapabilities", "planEvidence").addEdge("planEvidence", "collectEvidence").addEdge("collectEvidence", "assessEvidence").addConditionalEdges("assessEvidence", (s) => s.evidenceQuality?.enough ? "reason" : "reason").addEdge("reason", "validate").addEdge("validate", "__end__").compile();
