import { Annotation, StateGraph } from "@langchain/langgraph";
import { ChatGoogleGenerativeAI } from "@langchain/google-genai";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { mcpTool } from "./mcp";
import { EvidenceRegistry, discover, type EvidenceRequest, type Location } from "./evidence";
import { mireyeProvider, openCellIdProvider } from "./providers";
import type { ScoreResponse, IntelligenceLayers } from "@/lib/types";

export const SignalRentState = Annotation.Root({
  address: Annotation<string>(), lat: Annotation<number | undefined>(), lng: Annotation<number | undefined>(), carrier: Annotation<string | undefined>(), offeredRate: Annotation<number | undefined>(), buyoutAmount: Annotation<number | undefined>(),
  resolvedLat: Annotation<number>(), resolvedLng: Annotation<number>(), displayAddress: Annotation<string>(), evidence: Annotation<any[]>({ reducer: (a, b) => [...(a ?? []), ...(b ?? [])], default: () => [] }), capabilities: Annotation<any[]>(), result: Annotation<ScoreResponse | null>(), error: Annotation<string | null>(),
});
type State = typeof SignalRentState.State;
const registry = new EvidenceRegistry(); registry.addProvider(mireyeProvider); registry.addProvider(openCellIdProvider);
const unwrap = (v: any) => v?.structuredContent ?? v?.data ?? v?.content ?? v;

async function resolveNode(state: State) { const response = unwrap(await mcpTool("mireye_lookup", { input: state.lat !== undefined && state.lng !== undefined ? `${state.lat},${state.lng}` : state.address })); if (response?.disposition === "clarify") return { error: `Address is ambiguous: ${(response.candidates ?? []).map((c: any) => c.label).join(" or ")}` }; if (response?.disposition === "no_match") return { error: "Address not found." }; const location = response.location ?? response; return { resolvedLat: Number(location.lat), resolvedLng: Number(location.lng), displayAddress: location.displayAddress ?? location.label ?? state.address }; }
async function discoverNode() { return { capabilities: await discover(registry) }; }
async function collectNode(state: State) { const location: Location = { lat: state.resolvedLat, lng: state.resolvedLng, displayAddress: state.displayAddress }; const requests: EvidenceRequest[] = [{ concept: "population and demand", category: "population", importance: "high", reason: "estimate subscriber value" }, { concept: "terrain, hazards, utilities and access", category: "hazard", importance: "high", reason: "estimate construction and permitting friction" }, { concept: "nearby towers, carriers and coverage", category: "coverage", importance: "high", reason: "estimate coverage necessity and competition" }]; const batches = await Promise.all(registry.providerList().map((p) => p.collectEvidence(location, requests).catch((error) => [{ id: `${p.metadata().id}:error`, provider: p.metadata().id, category: "unknown" as const, summary: `Provider unavailable: ${String(error)}`, confidence: 0, importance: "high" as const, provenance: { source: p.metadata().name, retrievedAt: new Date().toISOString() }, timestamp: new Date().toISOString() }]))); const evidence = batches.flat(); registry.addEvidence(...evidence); return { evidence }; }
async function reasonNode(state: State) { const model = new ChatGoogleGenerativeAI({ model: "gemini-3.1-flash-lite", temperature: 0, apiKey: process.env.GEMINI_API_KEY }); const prompt = `Location: ${state.displayAddress} (${state.resolvedLat}, ${state.resolvedLng})\nCarrier: ${state.carrier ?? "unknown"}\nOffered rate: ${state.offeredRate ?? "not provided"}\nBuyout: ${state.buyoutAmount ?? "not provided"}\nDiscovered capabilities: ${JSON.stringify(state.capabilities)}\nEvidence registry: ${JSON.stringify(state.evidence, null, 2)}`; const message = await model.invoke([new SystemMessage("You are SignalRent's evidence-based valuation reasoner. Reason only from the evidence registry. Do not invent values, fields, providers, weights, scores, thresholds, or missing facts. Explain uncertainty, contradictions, missing evidence, strengths, weaknesses, negotiation leverage, and next steps. Return only <reasoning>...</reasoning><output>{valid ScoreResponse JSON}</output>."), new HumanMessage(prompt)]); const text = String(message.content); const output = text.match(/<output>([\s\S]*?)<\/output>/i)?.[1]; if (!output) throw new Error("Reasoner returned no output"); return { result: { ...JSON.parse(output), reasoning: text.match(/<reasoning>([\s\S]*?)<\/reasoning>/i)?.[1]?.trim() ?? "", intelligence: {} as IntelligenceLayers } as ScoreResponse }; }
async function validateNode(state: State) { if (!state.result) return { error: "Reasoner returned no result" }; return { result: state.result }; }

export const graph = new StateGraph(SignalRentState).addNode("resolveLocation", resolveNode).addNode("discoverCapabilities", discoverNode).addNode("collectEvidence", collectNode).addNode("reason", reasonNode).addNode("validate", validateNode).addEdge("__start__", "resolveLocation").addConditionalEdges("resolveLocation", (s) => s.error ? "__end__" : "discoverCapabilities").addEdge("discoverCapabilities", "collectEvidence").addEdge("collectEvidence", "reason").addEdge("reason", "validate").addEdge("validate", "__end__").compile();
